SC calls integration test
multiversx/mx-bridge-eth-go pull request #276
Opened 2023-12-14 16:38 UTC by iulianpascalau

- added SC call integration test
- fixed one related bug & added unit tests

2023-12-15 10:25 UTC, ccorcoveanu requested changes

2023-12-15 10:25 UTC, ccorcoveanu commented on integrationTests/mock/multiversXContractStateMock.go
> +		if bytes.Equal(from, mock.whitelistedEthSCAddress) {
The check should be done on `to` instead of `from` (for sc execution, is a transfer to a mvx smart contract) :D

2023-12-18 07:15 UTC, sasurobert approved these changes

2023-12-18 07:23 UTC, ccorcoveanu approved these changes

2023-12-18 08:17 UTC, merged